settings:
  title: 'Status Page'
  url: 'https://status.helloxue.org/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 15 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: ChatGPT # unique identifier
    name: ChatGPT
    description: 'OpenAI' # default=empty
    url: 'https://status.openai.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: Claude
    name: Claude
    description: 'Anthropic'
    url: 'https://status.anthropic.com/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true

  - id: www-helloxue-com
    name: HiX
    url: 'https://helloxue.com'
    method: GET
    expectStatus: 200
    linkable: false

  - id: blog-helloxue-com
    name: Blog
    url: 'https://blog.helloxue.com/'
    method: GET
    expectStatus: 200
    linkable: false

  - id: chat-helloxue-com
    name: Chat
    url: 'https://chat.helloxue.com/'
    method: GET
    expectStatus: 200
    linkable: false

  - id: shorten-helloxue-com
    name: Shorten
    url: 'https://shorten.helloxue.com/'
    method: GET
    expectStatus: 200
    linkable: false
